import applications_functional_analysis_differential_integral_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace applications_functional_analysis_differential_integral_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end applications_functional_analysis_differential_integral_canonical_lane_mathlib
end HautevilleHouse
